import React, { useRef, useEffect } from "react";
import Head from "next/head";
import Link from 'next/link';
import { gsap } from "gsap";
import styles from "../styles/Home.module.css";

export default function Home() {

  const tlOne = gsap.timeline({
    defaults: {
      duration: 1.5,
      ease: "power2.out"
    },
  });

  const linkWindow = useRef();

  useEffect(() => {
    tlOne.fromTo(
      linkWindow.current,
      {
        opacity: 0,
        x: 250,
      },
      {
        opacity: 1,
        x: 0,
      }
    );
  }); 

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.wrapper}>
        <div className={styles.linkWindow} ref={linkWindow}>
                <Link href='/register'>
                  <span className={styles.linkText}>Register</span>
                </Link>
                <Link href='/login'>
                  <span className={styles.linkText}>Login</span>
                </Link>              
                <Link href='/about'>
                  <span className={styles.linkText}>About</span>
                </Link>              
        </div>
      </div>
    </div>
  );
}
