import React from "react";
import Head from "next/head";
import Slider from "../components/Slider";
import styles from "../styles/Home.module.css";

export default function Home() {

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.wrapper}>
      <Slider />
        <div className={styles.logo}></div>
      </div>

    </div>
  );
}
