import Head from "next/head";
import Cookie from "../components/Cookie.js";
import styles from "@/styles/Home.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Cookie />
      <div className={styles.content}>
        <h1>Welcome!</h1>
        <p>Made with Next.js</p>
        <h2>AND</h2>
        <p>Green Sock (gsap)</p>
        <h2>Developed by</h2>
        <p>Michael Cuccia</p>
      </div>
    </div>
  );
}
