import Head from "next/head";
import dbConnect from "../utils/dbConnect";
import User from "../models/User";
import Cookie from "../components/Cookie.js";

export default function Home() {

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Cookie />
    </div>
  );
}

export async function getServerSideProps() {
  await dbConnect();

  const res = await User.find({});
  const users = JSON.stringify(res);

  console.log(users)

  return {
    props: {
      users,
    },
  };
}
