import React, { useEffect, useRef } from "react";
import { gsap } from "gsap";
import Head from "next/head";
import styles from "@/styles/Home.module.css";

export default function Home() {
  const mainRef = useRef();

  useEffect(() => {
    gsap.fromTo(
      mainRef.current,
      {
        opacity: 0,
      },
      {
        opacity: 1,
        duration: 1,
      }
    );
  });

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.main} ref={mainRef}>
        Hello from Index.js
      </div>
    </div>
  );
}
